
site = { bucket = "./public", entry-point = "workers-site" }
name = "pastebin"
main = "src/index.js"
compatibility_date = "2025-07-29"

kv_namespaces = [
    { binding = "Pastebin", id = "7511b61ec1a8423bb1903a4960ac7308" },
]

[site]
bucket = "./public"
