name = "pastebin-worker"
main = "worker/index.js"
compatibility_date = "2025-07-29"
account_id = "dd7ad106d2c75ed5b43e1fdb13293d57"
# disable dev subdomain
workers_dev = false

# Bind your KV namespace to `env.PASTES`
kv_namespaces = [
  { binding = "PASTES", id = "7511b61ec1a8423bb1903a4960ac7308" }
]

# Routes: API and slug fallback
routes = [
  { pattern = "paste.peme969.dev/api/*", script = "pastebin-worker" },
  { pattern = "paste.peme969.dev/api/*/*", script = "pastebin-worker" },
  { pattern = "paste.peme969.dev/delete", script = "pastebin-worker" },
  { pattern = "paste.peme969.dev/*", script = "pastebin-worker" }
]
